#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
KEYWORD=$1
#OPTION=$2

msg=$(node $DIR/workspace.js --path=~/code/shutterstock --keyword=$KEYWORD)
echo "$msg"
if [ "$(echo -e "$msg" | grep -E '^Here are')" ]
then
  printf "\nType the number to get there: "
  read OPTION
  msg2=$(node $DIR/workspace.js --path=~/code/shutterstock --keyword=$KEYWORD --option=$OPTION)
  if [ "$(echo -e "$msg2" | grep -E '^\/')" ]
  then
    cd $msg2
  else
    echo "$msg2"
  fi
fi

if [ "$(echo -e "$msg" | grep -E '^\/')" ]
then
  cd $msg
fi
