#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
K=$1
msg=$(perl $DIR/workspace.pl --keyword=$K)

if [ "$(echo -e "$msg" | grep -E '^1\. ')" ]
then
  echo "$msg"
  read OPTION
  msg2=$(perl $DIR/workspace.pl --keyword=$K --option=$OPTION) 
  if [ "$(echo -e "$msg2" | grep -E '^\/')" ]
  then
    cd $msg2
  else
    echo "$msg2"
  fi
fi

if [ "$(echo -e "$msg" | grep -E '^\/')" ]
then
  cd $msg
fi

